### ISSUE TITLE
Guidance on OTA Update on ESP32 via AWS IoT and Platform.IO

### ISSUE THREAD

**Issue by FanuelConrad** [maxgerhardt/pio-espidf-aws-mqtt-ota#1]
Hello,
I'd like to be guided on how to perform OTA update on ESP32 via AWS IoT and Platform.IO
Any response will be highly appreciated

**Comment by maxgerhardt** [comment]
This repo is just the PlatformIO-compilable firmware posted at https://github.com/espressif/esp-aws-iot/tree/master/examples/ota/ota_mqtt, did you follow all the steps linked in there to obtain the certificates etc?

**Comment by FanuelConrad** [comment]
What I needed is using the platform folder structure to perform OTA instead of porting the ESP IDF files for OTA.
I need a method that utilizes Platform.IO for the OTA function so that I can just maintain using C++ for my project since I'm not conversant with C.

**Comment by maxgerhardt** [comment]
>the platform folder structure 

I'm not sure what you're referring to.

If you don't want to use ESP-IDF and .c, you can also use what Arduino-ESP32 has to offer with [regular OTA updates](https://github.com/espressif/arduino-esp32/tree/master/libraries/ArduinoOTA/examples/BasicOTA) ([PIO docs](https://docs.platformio.org/en/latest/platforms/espressif32.html#using-built-in-local-solution)), but that doesn't use AWS.
