### ISSUE TITLE
Port to the Arduino framework?

### ISSUE THREAD

**Issue by TT-ZX** [maxgerhardt/pio-espidf-aws-mqtt-ota#2]
How much work would it be to port this over to the PlatformIO Arduino framework?

**Comment by maxgerhardt** [comment]
Arduino-ESP32 uses ESP-IDF as a base, and PIO can compile in both the ESP-IDF and Arduino core (as a component), like https://github.com/platformio/platform-espressif32/tree/develop/examples/espidf-arduino-blink shows. Have you tried that route?

**Comment by TT-ZX** [comment]
`framework = arduino, espidf`
That actually worked.  I didn't know that was possible.  Thanks for your help!
